### ISSUE TITLE
Collapse and Expand VerticalNav through code

### ISSUE THREAD

**Issue by urdeveloper** [patternfly/patternfly-ng#438]
I was wondering if there's a way to collapse and expand the VerticalNav through the code. Right now it's only possible by clicking on humbugger menu. 

I noticed there are two methods (expandMenu and CollapseMenu) but both are private:
https://github.com/patternfly/patternfly-ng/blob/7a1904b00703dea20bff07d033ea62f843048745/src/app/navigation/vertical-navigation/vertical-navigation.component.ts#L629

Will be happy to send a PR if you're willing to make the methods public.

**Comment by dlabrecq** [comment]
I don't have an issue making these methods public. However, I would like to first understand why you need to open/close the menu programmatically?

**Comment by urdeveloper** [comment]
The use case is to persist the NavBar state (collapsed/expanded) so the user won't need to collapse the NavBar every time the page reloads.
Please see the PatternFly [example](https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html) , collapse the menu and refresh the page.

**Comment by dlabrecq** [comment]
I'm wondering if we can provide an attribute to set the initial state? We already use an internal property we could expose. Something like:

`<pfng-vertical-navigation [explicitCollapse]="true"...`

That way the menu renders collapsed instead of forcing it to close after briefly shown open? This would also allow the mobile state to override that.

Or would you prefer to call the methods instead?

**Comment by urdeveloper** [comment]
That would do it. Thanks!

**Comment by dlabrecq** [comment]
I added a new showMenuCollapsed attribute.

https://github.com/patternfly/patternfly-ng/pull/441
