### ISSUE TITLE
Test pages

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-ng#9]
Since this is a PatternFly repo, it is important that designers are able to review the patternfly-ng implementations during the PR process against our design standards.  What tooling would everyone suggest in order to allow designers to see the Pattern UI for reviewing the implementation during the pull request?

**Comment by dgutride** [comment]
There are a few options - this is one I just found that looks interesting:  https://github.com/synapse-wireless-labs/component-lab

**Comment by dlabrecq** [comment]
At first glance, I like this because it feels similar to Story book. Although, Storybook provides links to documentation, knobs to dynamically change the example, etc.

I noticed that their example has an object literal, named context, which is fine for providing variables like a button label. However, the examples I'd like to create have much more config than that and some really need a controller. The ngDocs for APF allowed us to create very robust examples, which I'd like to carry forward.

I suppose we could create a component to wrap a controller, if needed, and add that to the template instead?

**Comment by LHinson** [comment]
@dgutride the screenshot of it looks nice. is there an example of this anywhere we can visit?

**Comment by dgutride** [comment]
We've created a site that is accessible via rawgit for viewing the components:  https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/ - moving to closed
